### ISSUE TITLE
small nit - you named your script installLxdManger.sh - should be installLxdManager.sh right?

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdManager#19]
curl https://raw.githubusercontent.com/turtle0x1/LxdManager/master/examples/install_with_clone.sh >> installLxdManger.sh

Shouldn't that be renamed:

curl https://raw.githubusercontent.com/turtle0x1/LxdManager/master/examples/install_with_clone.sh >> installLxdManager.sh

I mistype Manager as Manger all the time so I tend to see that :-).

**Comment by turtle0x1** [comment]
Thanks for that :)
