### ISSUE TITLE
When  adding a Host what is the "trust password"

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdManager#20]
When  adding a Host what is the "trust password" ... are you referring to the password entered with doing LXD INIT and permitting LXD access over the network/internet ?  or something else?

brian

**Comment by bmullan** [comment]
<solved> ... I just tried using the LXD init "trust password" and that worked.

You might want to add that note to your Readme for those relatively new to LXD so they know what to do.

**Comment by turtle0x1** [comment]
Sure it was just about to response good idea!
