### ISSUE TITLE
Will the capability to copy/move a container from Server A to Server B be implemented?

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdManager#21]
I now have 2 LXD servers configured.
But will you be adding the capabilty to copy/move a container from Server A to Server B ?

brian

**Comment by turtle0x1** [comment]
Yeah you can currently click the "migrate" button but its a bit hit and miss;

It depends on having `criu` (at least when this project started) installed and other dependencies so you can give it ago (it will always return success even if it didn't)

**Comment by bmullan** [comment]
Per Stephane Graber's old post:
https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/

> **Copying containers**
> 
> Copying containers between hosts is as easy as it sounds:
> 
> **lxc copy foo:c1 c2**
> 
> And you’ll have a new local container called “c2” created from a copy of the remote “c1” container. This requires “c1” to be stopped first, but you could just copy a snapshot instead and do it while the source container is running:
> 
> **lxc snapshot foo:c1 current
> lxc copy foo:c1/current c3**
> 
> **Moving containers**
> 
> Unless you’re doing live migration (which will be covered in a later post), you have to stop the source container prior to moving it, after which everything works as you’d expect.
> 
> **lxc stop foo:c1
> lxc move foo:c1 local:**
> 
> This example is functionally identical to:
> 
> **lxc stop foo:c1
> lxc move foo:c1 c1**

**Comment by bmullan** [comment]
Youo really only need CRIU for "live" migration.  But CRIU still has some problems.  However, if you don't need to migrate a live container the above/previous comment's contents work well.

**Comment by turtle0x1** [comment]
So you want to redeploy a snapshot to another machine ? Not really a problem; 

The only problem I see with this is that the two hosts have to be connected to each other which has be done by the sys admin instead of by the application; For this reason I find it annoying as its another thing to warn and document but you asked so you get!

**Comment by bmullan** [comment]
Not in my experience.   I have cloud servers where when I do

lxd init

I answer the question "do you want lxd to be available over the net" yes,
and give it a trust password

I do the same locally

Obviously port 8443 or whatever port you use has to be "open" but then the
copy & move works

I'm on my phone right now so I can't t remember if you have to "add" the
remote as an image server or not locally... But this works as I have a
cloud server I setup to do thi with for container backup purposes

**Comment by bmullan** [comment]
Email me w your ph # or can send you mine if you want to talk.   I am in
Raleigh NC

**Comment by turtle0x1** [comment]
Sorry whats a ph # ?

**Comment by bmullan** [comment]
phone number

**Comment by bmullan** [comment]
If I remember right this is what I did to set mine up tTo add the remote
repository so you can copy images to/from it

Say you have two machines with LXD installed, your local machine and a
remote host that we’ll call “ciab-repo”.

First you need to make sure that “ciab-repo” is listening to the network
and has a password set, so get a remote shell on it and run:

*lxc config set core.https_address [::]:8443
lxc config set core.trust_password <something-secure>*

*Now on your local LXD,* ou just need to make it visible to the network so
we can transfer containers and images from it:

*lxc config set core.https_address [::]:8443*

Now that the daemon configuration is done on both ends, you can add
“ciab-repo” to your local LXD with:

*lxc remote add ciab-repo 1.2.3.4*

assuming IP of the repo is 1.2.3.4

After that you can copy to/from the ciab-repo using ordinary lxd cli
commands:

*lxc copy local-cn1 ciab-repo:remote-cn1*

or copy and image from the repo to the local machine

*lxc copy ciab-repo:remote-cn1 local-cn1*

*now if you do a local:*

*lxc list*

you should see a container named "local-cn1"

again this assumes you have opened or port forward port 8443 on
local/remote routers/hosts

Brian

**Comment by turtle0x1** [comment]
Thanks alot for the suggestion for how to setup the hosts to implement this! 

I live in the UK so international calls could be quite expensive, I posted on the sub-reddit /r/lxd where it appears you are the administrator so maybe we could message through there to organize Skype or some other online. 

Im going to copy these instructions into my issue #3 which is for fixing container migration, ill probably take a look tomorrow!

**Comment by bmullan** [comment]
Try out what I sent as I typed most of that from memory
