### ISSUE TITLE
There should be an uninstall script for LxdManager 

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdManager#22]
Do you think there should be an uninstall script for LxdManager to completely remove what the Install.sh script puts on a system.

**Comment by turtle0x1** [comment]
That is why it comes with a warning that it should be installed in a container, I feel like uninstalling MySQL from peoples hosts could be dangerous I guess I could add options; 

In the mean time you could probably just invert the install script something like; 

```
sudo apt-get purge all-the-deps
sudo rm -rf /var/www/LxdManager
sudo rm -rf /etc/apache2/sites-available/lxd_manager.conf
```

**Comment by bmullan** [comment]
no, you are right....

you do warn them in the README

**Comment by bmullan** [comment]
I
