### ISSUE TITLE
I just installed the updated code in a fresh LXD container & think something is broken

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdManager#23]
Ubuntu 18.04 host
\# launch an ubuntu 18.04 container
**lxc launch ubuntu:bionic lxdmanager
lxc exec lxdmanager bash**
**apt update && apt upgrade -y**
\# get install script
**curl https://raw.githubusercontent.com/turtle0x1/LxdManager/master/examples/install_with_clone.sh >> installLxdManager.sh**
**chmod +x installLxdManager.sh**
\# execute install script
**./installLxdManager.sh**
\# open some ports in the container
**ufw allow https
ufw allow 3000
ufw allow 80
ufw alllow 8080**
\# after installation using either Chromium or Firefox I can had the local host as a Server but
\# after that I can't click to add a 2nd LXD host (nothing happens) and also some of the buttons just 
\# stop working .. ie if I click on them they do nothing.

\# before the most recent change(s) this seemed to all work correctly.

**Comment by bmullan** [comment]
By the way... I don't have to go to  https://<ip_address>:3000 first to accept the cert and then
go to https://<ip_address>

In either firefox or chromium just going to https://<ip_address> will initially prompt me to accept the cert and after doing that pass me to lxdmanager

**Comment by turtle0x1** [comment]
You need to go to port :3000 to accept the node certificate this will probably fix your issue!

**Comment by bmullan** [comment]
see previous comment.   Firefox & Chrome will automatically prompt for accepting the cert if you just go to the <ip_address> alone.

If I point to:

https://<ip_address>:3000

I get an error:

> 
> Unable to connect
> 
> Firefox can’t establish a connection to the server at 10.105.172.50:3000.
> 
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.
>     If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by turtle0x1** [comment]
Ah okay thats different `forever` didn't start the node script could go into the bash shell in the container and put the output of `forever list`

**Comment by bmullan** [comment]
root@lxdmanager:~# forever list
info:    No forever processes running

**Comment by turtle0x1** [comment]
Can you run `node /var/www/LxdManager/node/events.js`

**Comment by bmullan** [comment]
remember lxdmanager let me add the 1st LXD Host server but it didn't list any of the 24 containers on that Host/Server

**Comment by turtle0x1** [comment]
Its because the node server isn't running its causing the javascript execution to fail on the client side which loads the rest of the containers, the node connection only starts after you add your first server!

**Comment by turtle0x1** [comment]
Did you reboot the container after install ?

**Comment by turtle0x1** [comment]
Im going to close this out now if its all gone okay ?

**Comment by bmullan** [comment]
Ok... I'll let you know if I encounter anything.
